var MenuData = require('../models/MenuData');
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/SMAfoms');

mongoose.connect(process.env.MongoDB_ADD).then(()=>{
    console.log("Connection Successful")
}).catch((e)=>{
    console.log(e);
});

var MenuDatas = [
// Burger
  new MenuData({
    name: "Aloo Tikki Burger",
    price: 90,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713909446/foms/burgers/aloo-tikki-burger_zooik7.jpgp",
    category: "Burger",
  }),
  new MenuData({
    name: "Veg Cheese Aloo Tikki",
    price: 130,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/veg-cheese-aloo-tikki_nz1hyp.webp",
    category: "Burger",
  }),
  new MenuData({
    name: "Tandoori butter cheese burger",
    price: 120,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/tandoori-butter-cheese-burger_lipqfb.webp",
    category: "Burger",
  }),
  new MenuData({
    name: "Makhani cheese ball burger",
    price: 120,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/makhani-cheese-ball-burger_ruhz5r.jpg",
    category: "Burger",
  }),
  new MenuData({
    name: "Schezwan cheese burger",
    price: 120,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/schezwan-cheese-burger_burgzg.jpg",
    category: "Burger",
  }),
  new MenuData({
    name: "Paneer cheese burger",
    price: 120,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/paneer-cheese-burger_fbvrvs.webp",
    category: "Burger",
  }),
  new MenuData({
    name: "Corn Cheese Burger",
    price: 120,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/corn-cheese-burger_avovsl.png",
    category: "Burger",
  }),
  new MenuData({
    name: "Cheese Peri Peri Aloo Tikki",
    price: 145,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/cheese-peri-peri-aloo-tikki_sqanhc.webp",
    category: "Burger",
  }),
  new MenuData({
    name: "Tandoori paneer cheese burger",
    price: 135,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/tandoori-paneer-cheese-burger_lykrgp.png",
    category: "Burger",
  }),
  new MenuData({
    name: "Makhani Paneer cheese burger",
    price: 135,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713906452/foms/burgers/makhani-paneer-cheese-burger_x28auw.jpg",
    category: "Burger",
  }),
  new MenuData({
    name: "Schezwan Paneer Cheese Burger",
    price: 135,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/schezwan-paneer-cheese-burger_wtiri3.webp",
    category: "Burger",
  }),
  new MenuData({
    name: "Peri Peri paneer cheese burger",
    price: 135,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/peri-peri-paneer-cheese-burger_ia3rgk.png",
    category: "Burger",
  }),
  new MenuData({
    name: "Special Maharaja Cheese Burger",
    price: 150,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/burgers/special-maharaja-cheese-burger_vlhgcs.webp",
    category: "Burger",
  }),
  
//French Fries
new MenuData({
  name: "Masala French Fries",
  price: 105,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/french_fries/masala-french-fries_iczrun.jpg",
  category: "French fries",
}),
new MenuData({
  name: "Special french fries with Tandoori Mayo",
  price: 120,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/french_fries/special-french-fries-with-tandoori-mayo_rrtcvi.webp",
  category: "French fries",
}),
new MenuData({
  name: "Special French Fries With Makhani Mayo",
  price: 120,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713906545/foms/french_fries/special-french-fries-with-makhani-mayo_n1476c.jpg",
  category: "French fries",
}),
new MenuData({
  name: "Special French Fries With Schezwan Mayo",
  price: 120,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/french_fries/special-french-fries-with-schezwan-mayo_n3cfhm.jpg",
  category: "French fries",
}),
new MenuData({
  name: "Special french fries with Peri Peri mayo",
  price: 120,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/french_fries/french-fries-with-peri-peri-mayo_cagiu7.webp",
  category: "French fries",
}),

// Garlic Bread
new MenuData({
  name: "Cheese Garlic Bread",
  price: 120,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/garlic_breads/cheese-garlic-bread_v5pid7.jpg",
  category: "Garlic bread",
}),
new MenuData({
  name: "Paneer Cheese Garlic Bread",
  price: 135,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/garlic_breads/paneer-cheese-garlic-bread_oplesd.jpg",
  category: "Garlic bread",
}),
new MenuData({
  name: "Hot Pizza special garlic bread",
  price: 150,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713906735/foms/garlic_breads/hot-pizza-special-garlic-bread_v30h7v.jpg",
  category: "Garlic bread",
}),
new MenuData({
  name: "Special Cheesy Stick Garlic Bread Stuffed",
  price: 225,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/garlic_breads/special-cheesy-stick-garlic-bread-stuffed_b4k0zm.jpg",
  category: "Garlic bread",
}),
new MenuData({
  name: "Special cheesy paneer stick garlic bread stuffed",
  price: 240,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/garlic_breads/special-cheesy-paneer-stick-garlic-bread-stuffed_ius7y6.webp",
  category: "Garlic bread",
}),

//Patties
new MenuData({
  name: "Aloo Patties",
  price: 45,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/aloo-patties_cvnxzt.png",
  category: "Patties",
}),
new MenuData({
  name: "Vegetable masala patties",
  price: 90,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/vegetable-masala-patties_bemix8.webp",
  category: "Patties",
}),
new MenuData({
  name: "Veg Mayo masala patties",
  price: 120,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/veg-mayo-masala-patties_bf1ker.jpg",
  category: "Patties",
}),
new MenuData({
  name: "Cheese Mayo masala",
  price: 150,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/cheese-mayo-masala_gkpcm2.webp",
  category: "Patties",
}),
new MenuData({
  name: "Veg Paneer Cheese Patties",
  price: 165,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/veg-panner-cheese-patties_vacisn.jpg",
  category: "Patties",
}),
new MenuData({
  name: "Special Punjabi Paneer Tandoori Patties",
  price: 180,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/special-punjabi-paneer-tandoori-patties_yvmwz6.jpg",
  category: "Patties",
}),
new MenuData({
  name: "Special tangy Makhani cheese paneer patties",
  price: 180,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/special-tangy-makhani-cheese-paneer-patties_duofky.jpg",
  category: "Patties",
}),
new MenuData({
  name: "Paneer Peri Peri Kingdom Patties",
  price: 180,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/paneer-peri-peri-kingdom-patties_ourgeq.webp",
  category: "Patties",
}),
new MenuData({
  name: "Special Schezwan patties",
  price: 180,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/special-schezwan-patties_bkrrig.jpg",
  category: "Patties",
}),
new MenuData({
  name: "Special thousand Iceland labalab patties",
  price: 210,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/special-thousand-Iceland-labalab-patties_gajfcy.png",
  category: "Patties",
}),
new MenuData({
  name: "Special Bahubali paneer cheese patties",
  price: 210,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/foms/patties/special-bahubali-paneer-cheese-patties_vbcclf.jpg",
  category: "Patties",
}),

//Pizza
  new MenuData({
    name: "Vegetable cheese",
    price: 185,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903087/foms/pizzas/vegetable-cheese_sf7m4g.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Jain spicy",
    price: 195,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903046/foms/pizzas/jain-spicy_l17cas.webp",
    category: "Pizza",
}),
new MenuData({
    name: "Veg paneer cheese",
    price: 205,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903099/foms/pizzas/veg-paneer-cheese_d6kfci.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Jain paneer",
    price: 205,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903043/foms/pizzas/jain-paneer_mgfnqf.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Hot potato ( Double Cheese )",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903043/foms/pizzas/hot-potato_double-cheese_ahqovo.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Veg American Corn With Paneer ( Double Cheese )",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903073/foms/pizzas/special-veg-american-corn-with-paneer-double-cheese_jrhdly.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special chatpata Chaat paneer ( Double Cheese )",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903049/foms/pizzas/special-chatpata-chaat-paneer_double-cheese_hdzgxm.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special veg paneer cheesey peasy ( Double Cheese )",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903058/foms/pizzas/special-veg-paneer-cheesey-peasy-double-cheese_aslq2k.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Hot And Sweet Chocolate With Choco Butter Deep",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903058/foms/pizzas/special-hot-and-sweet-chocolate-with-choco-butter-deep_j7wijd.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special olive pizza",
    price: 250,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903069/foms/pizzas/special-olive-pizza_ztubit.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Jalapeno pizza",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903062/foms/pizzas/special-jalapeno-pizza_ubgbwe.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special mexican pizza",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903064/foms/pizzas/special-mexican-pizza_mhkexg.webp",
    category: "Pizza",
}),
new MenuData({
    name: "Special Garlic Pizza",
    price: 225,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903055/foms/pizzas/special-garlic-pizza_zfzb0h.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Cheese Burst ( Double Cheese )",
    price: 250,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903053/foms/pizzas/special-cheese-burst-double-cheese_non6ih.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Paneer Tikka ( Double Cheese )",
    price: 265,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903071/foms/pizzas/special-paneer-tikka-double-cheese_anuuog.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Hot Cocktail ( Double Cheese )",
    price: 265,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903060/foms/pizzas/special-hot-cocktail-double-cheese_kob3fj.webp",
    category: "Pizza",
}),
new MenuData({
    name: "Special Paneer Peri Peri Golden Corn",
    price: 265,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903076/foms/pizzas/special-paneer-peri-peri-golden-corn_jxjvqe.webp",
    category: "Pizza",
}),
new MenuData({
    name: "Special Paneer Makhani Chatkara Pizza",
    price: 240,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903071/foms/pizzas/special-paneer-makhani-chatkara-pizza_fpkvbg.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Roasted Tandoori Paneer Pizza",
    price: 240,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903097/foms/pizzas/special-roasted-tandoori-paneer-pizza_oxf8zx.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Schezwan pizza",
    price: 240,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903080/foms/pizzas/special-schezwan-pizza_nrlqr1.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Paneer Marwadi Tikka",
    price: 280,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903078/foms/pizzas/special-paneer-marwadi-tikka_vqkdes.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special spicy cheesy chilli garlic",
    price: 280,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903082/foms/pizzas/special-spicy-cheesy-chilli-garlic_vfcamz.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special Thin Crust Pizza",
    price: 255,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903066/foms/pizzas/special-thin-crust-pizza_a6xvbj.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "This Special Macaroni Pasta Pizza",
    price: 270,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903085/foms/pizzas/this-special-macaroni-pasta-pizza_zbbbn4.webp",
    category: "Pizza",
}),
new MenuData({
    name: "Special Mozzarella cheese pizza",
    price: 270,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903064/foms/pizzas/special-mozzarella-cheese-pizza_kadykr.jpg",
    category: "Pizza",
}),
new MenuData({
    name: "Special baby corn pizza",
    price: 270,
    isVeg: 1,
    image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903049/foms/pizzas/special-baby-corn-pizza_t6lo1k.jpg",
    category: "Pizza",
}),

//Sandwich
new MenuData({
  name: "Special Veg Cheese Sandwich",
  price: 105,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903029/foms/sandwiches/veg-cheese-grilled_-sandwich_czx7xp.webp",
  category: "Sandwich",
}),
new MenuData({
  name: "Special mix mashup grilled Sandwich",
  price: 150,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903016/foms/sandwiches/special-mix-mashup-grilled-sandwich_buyhp2.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special Loaded Cheese Grill Triple Bread ",
  price: 190,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903013/foms/sandwiches/special-loaded-cheese-grill-triple-bread_upbfbc.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special Veg Jumbo Cheese Grilled Sandwich",
  price: 180,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903027/foms/sandwiches/special-veg-jumbo-cheese-grilled-sandwich_tzcd3b.webp",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Chocolate Grill ",
  price: 205,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903010/foms/sandwiches/jumbo-chocolate-grill_jpb6px.webp",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Aloo Masala Grill ",
  price: 220,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902987/foms/sandwiches/jumbo-aloo-masala-grill_wkkx8a.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Paneer Cheese Grill ",
  price: 220,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903010/foms/sandwiches/jumbo-paneer-cheese-grill_kbz7cl.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Pasta Tandoori Paneer Cheese Grill ",
  price: 235,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902999/foms/sandwiches/jumbo-pasta-tandoori-paneer-cheese-grill_mmtscu.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Paneer Makhani Paradise grill ",
  price: 235,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902996/foms/sandwiches/jumbo-paneer-makhani-paradise_-grill-sandwich_vs60lz.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Schezwan Paneer Grill ",
  price: 235,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902999/foms/sandwiches/jumbo-pasta-tandoori-paneer-cheese-grill_mmtscu.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo deluxe paneer peri Peri cheese grill ",
  price: 235,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903011/foms/sandwiches/jumbo-deluxe-paneer-peri-peri-cheese-grill_j7ngvd.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Lababdar Cheese Paneer With Chili Garlic Grill ",
  price: 235,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903010/foms/sandwiches/jumbo-lababdar-cheese-paneer_-with-chili-garlic-grill_bj3wfg.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo ( Double Cheese ) grill ",
  price: 235,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902986/foms/sandwiches/jumbo_double-cheese_grill_mvzlrz.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Jumbo Mix Mashup Grilled Sandwich",
  price: 225,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903006/foms/sandwiches/jumbo-mix-mashup-grilled-sandwich_asw7y8.webp",
  category: "Sandwich",
}),
new MenuData({
  name: "Nutella Jam Sandwich",
  price: 105,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903003/foms/sandwiches/nutella-jam-sandwich_bvfwr3.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Chocolate grilled Sandwich",
  price: 105,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902983/foms/sandwiches/chocolate-grilled-sandwich_f4ltbm.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Veg Cheese Grilled Sandwich",
  price: 105,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903025/foms/sandwiches/special-veg-cheese-sandwich_pj3jkl.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Aloo masala grilled Sandwich",
  price: 130,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902987/foms/sandwiches/jumbo-aloo-masala-grill_wkkx8a.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special paneer cheese grill ",
  price: 145,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903010/foms/sandwiches/jumbo-paneer-cheese-grill_kbz7cl.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special Paper Tandoori Paneer Cheese Grill ",
  price: 160,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903022/foms/sandwiches/special-paper-tandoori-panner-cheese-grill_zjjr98.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special Paneer Makhani Paradise Grill ",
  price: 160,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903020/foms/sandwiches/special-paneer-makhani-paradise-grill_gwui4u.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special Deluxe Paneer Peri Peri Cheese Grill ",
  price: 160,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903011/foms/sandwiches/jumbo-deluxe-paneer-peri-peri-cheese-grill_j7ngvd.jpg",
  category: "Sandwich",
}),
new MenuData({
  name: "Special about cheese paneer with Chili garlic grill ",
  price: 160,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713903010/foms/sandwiches/jumbo-deluxe-paneer-peri-peri-cheese-grill_j7ngvd.jpg",
  category: "Sandwich",
}),

//Shake
new MenuData({
  name: "Pineapple Shake",
  price: 90,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902963/foms/shakes/pineapple-shake_avkkyr.jpg",
  category: "Shake",
}),
new MenuData({
  name: "Strawberry Shake",
  price: 90,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902965/foms/shakes/strawberry-shake_risrat.jpg",
  category: "Shake",
}),
new MenuData({
  name: "Black currant Shake",
  price: 90,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902956/foms/shakes/black-currant-shake_ieqnwp.avif",
  category: "Shake",
}),
new MenuData({
  name: "Mango Shake",
  price: 90,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902959/foms/shakes/mango-shake_jex6oq.jpg",
  category: "Shake",
}),
new MenuData({
  name: "Kiwi Shake",
  price: 90,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902954/foms/shakes/kiwi-shake_erckfy.jpg",
  category: "Shake",
}),
new MenuData({
  name: "Oreo Shake",
  price: 105,
  isVeg: 1,
  image: "https://res.cloudinary.com/dptn8q20a/image/upload/v1713902961/foms/shakes/oreo-shake_etrlah.jpg",
  category: "Shake",
}),
]

async function saveMenuDatas() {
    try {
        for (let i = 0; i < MenuDatas.length; i++) {
            const result = await MenuDatas[i].save();
            console.log(`Saved MenuData: ${result}`);
        }
        mongoose.disconnect();
    } catch (err) {
        console.error('Error saving MenuDatas:', err);
        mongoose.disconnect();
    }
}

saveMenuDatas();
